# ## Model ##
# name: "ResNet18_base"
# pretrained: False
# l2_norm: False
# use_bn_layer: False
# # freeze_layer: False  # or ['fc']
# last_feature_dim: 512

## Model ##
name: "personalized_resnet18"  # âœ… Ensure this matches the registered name!
pretrained: False
l2_norm: False
use_bn_layer: False
last_feature_dim: 512

